### ISSUE TITLE
Exits panel doesn't refresh when switching rooms

### ISSUE THREAD

**Issue by patrickgh3** [le-doux/bitsy#59] opened 2019-11-27 21:52 UTC
When I click "next room" or "previous room" in the rooms panel, and the exits & endings panel is open, that panel doesn't update and still shows an exit from the previously open room. It seems to update properly when I then click "next" and "previous" in it though.

This was confusing to me because I hadn't learned that the exits & endings panel only showed exits and endings _of that room_ instead of throughout the game. Related suggestion about that: it might be nice to put a line of text in the exits & endings panel like "2 exits/endings involving this room" to make that clear and avoid the confusion I had of "where did my exits go? why are they only showing up sometimes?"

Thanks for making Bitsy! I'm really enjoying making a game for the soup bitsy jam! :)

**Comment by zachThePerson** [comment] 2019-12-27 07:25
The exits and endings panel doesn't show the exits/endings from the current room, but instead the most recently selected exit/ending. This way you can select one end of an exit, go to another room, click _move_ and place that exit in a room that wasn't directly connected before.

When you click on an exit in another room, it should update properly as this is the intended behavior.

**Comment by le-doux** [comment] 2022-08-06 21:49
thanks for reporting this issue @patrickgh3  - as @zachHixson said this is the intended behavior, but I get it can be a bit confusing, which is something I'll keep in mind for future updates to that tool. for now I'm closing this bug since it's working as intended :)

**Closed by le-doux** 2022-08-06 21:49 UTC
